# Generated by Django 4.0.3 on 2022-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='alias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('SAVINGS_ACCOUNT', '자유입출금'), ('INSTALLMENT_SAVING', '적금'), ('TIME_DEPOSIT', '예금')], default='SAVINGS_ACCOUNT', max_length=30),
        ),
        migrations.AddField(
            model_name='deposit',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshot',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
