# Generated by Django 4.0.3 on 2022-03-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_snapshot_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
