# Generated by Django 4.0.3 on 2022-03-13 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_account_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
