# Generated by Django 4.0.3 on 2022-12-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_account_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.FloatField(),
        ),
    ]
